Fix sorting tags by name
For still unknown reason sorting by tag name breaks if there are more than 999 TagOnFile relations per query.

    thread 'tokio-runtime-worker' panicked at 'no entry found for key', query-engine\prisma-models\src\record.rs:67:33
    note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
    Error:
    Invalid `this.prisma.tagsOnFiles.findMany()` invocation in
    C:\Github\laputin\oclif\src\laputin\library.ts:287:63

    284 }, []);
    285
    286 for (const chunk of fileIdsInChunks) {
    → 287     const tagsOnFiles = await this.prisma.tagsOnFiles.findMany(
    no entry found for key

    This is a non-recoverable error which probably happens when the Prisma Query Engine has a panic.

    https://github.com/prisma/prisma/issues/new?body=Hi+Prisma+Team%21+My+Prisma+Client+just+crashed.+This+is+the+report%3A%0A%23%23+Versions%0A%0A%7C+Name++++++++++++%7C+Version++++++++++++%7C%0A%7C-----------------%7C--------------------%7C%0A%7C+Node++++++++++++%7C+v16.18.0+++++++++++%7C+%0A%7C+OS++++++++++++++%7C+windows++++++++++++%7C%0A%7C+Prisma+Client+++%7C+4.5.0++++++++++++++%7C%0A%7C+Query+Engine++++%7C+0362da9eebca54d94c8ef5edd3b2e90af99ba452%7C%0A%7C+Database++++++++%7C+sqlite+++++++++++++%7C%0A%0A%0A%0A%23%23+Logs%0A%60%60%60%0A%28%0A++++++++++++SELECT+File.id%2C+File.hash%2C+File.path%2C+File.size%2C+File.metadata%2C+File.type%0A++++++++++++FROM+File%0A++++++++++++WHERE+1+%3D+1%0A+++++++++++++AND+active+%3D+1+%0A++++++++++++%0A++++++++++++%0A++++++++++++%0A++++++++++++%0A++++++++++++%0A++++++++++++%0A++++++++++++%0A++++++++++++ORDER+BY+File.path%2C+%5B%5D%29%0Aprisma%3Aclient+Prisma+Client+call%3A%0Aprisma%3Aclient%3AlibraryEngine%3Aloader+Searching+for+Query+Engine+Library+in+C%3A%5CGithub%5Claputin%5Coclif%5Cnode_modules%5C.prisma%5Cclient%0Aprisma%3Aclient%3AlibraryEngine%3Aloader+loadEngine+using+C%3A%5CGithub%5Claputin%5Coclif%5Cnode_modules%5C.prisma%5Cclient%5Cquery_engine-windows.dll.node%0Aprisma%3Aclient%3AlibraryEngine+sending+request%2C+this.libraryStarted%3A+false%0Aprisma%3Aclient%3AlibraryEngine+library+starting%0Aprisma%3Aclient%3AlibraryEngine+library+started%0Aprisma%3Aclient%3AlibraryEngine+sending+request%2C+this.libraryStarted%3A+true%0A%60%60%60%0A%0A%23%23+Client+Snippet%0A%60%60%60ts%0A%2F%2F+PLEASE+FILL+YOUR+CODE+SNIPPET+HERE%0A%60%60%60%0A%0A%23%23+Schema%0A%60%60%60prisma%0A%2F%2F+PLEASE+ADD+YOUR+SCHEMA+HERE+IF+POSSIBLE%0A%60%60%60%0A%0A%23%23+Prisma+Engine+Query%0A%60%60%60%0A%7B%22X%22%3A%7B%7D%7D%0A%60%60%60%0A&title=no+entry+found+for+key&template=bug_report.md

    If you want the Prisma team to look into it, please open the link above 🙏
    To increase the chance of success, please post your schema and a snippet of
    how you used Prisma Client in the issue.

        at RequestHandler.handleRequestError (C:\Github\laputin\oclif\node_modules\@prisma\client\runtime\index.js:30881:13)
        at RequestHandler.request (C:\Github\laputin\oclif\node_modules\@prisma\client\runtime\index.js:30856:12)
        at async PrismaClient._request (C:\Github\laputin\oclif\node_modules\@prisma\client\runtime\index.js:31836:16)
        at async Library.getFilesViaSql (C:\Github\laputin\oclif\src\laputin\library.ts:287:33)
        at async FileLibrary.load (C:\Github\laputin\oclif\src\laputin\filelibrary.ts:49:31)
        at async Laputin.loadFiles (C:\Github\laputin\oclif\src\laputin\laputin.ts:85:9)
        at async Start.run (C:\Github\laputin\oclif\src\commands\start.ts:51:9)
        at async Start._run (C:\Github\laputin\oclif\node_modules\@oclif\core\lib\command.js:80:22)
        at async Config.runCommand (C:\Github\laputin\oclif\node_modules\@oclif\core\lib\config\config.js:272:25)
        at async Object.run (C:\Github\laputin\oclif\node_modules\@oclif\core\lib\main.js:76:5)